# Generated by Django 2.2 on 2020-05-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boredom_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='reward',
        ),
        migrations.AddField(
            model_name='user',
            name='reward',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
